### ISSUE TITLE
Generated SubFlow Data - Only Appears as Subflow reference 

### ISSUE THREAD

**Issue by SehunBaba** [CuriositySoftwareIreland/knowledge_and_support#5]
Here's the data preview of the model variables 

![](https://user-images.githubusercontent.com/37783660/169064942-78402a23-54aa-4538-97a8-607f32d0f0de.png)

Here's the data preview of the subflow variables 

![](https://user-images.githubusercontent.com/37783660/169065033-25d7660d-a445-4b2c-a9c3-3127b7fc2f10.png)

As you can see the data appears correctly in the subflow but in the model itself we only see the subflow reference. 

If we run the   `generate data from CSV` job we get the same result.

┆Issue is synchronized with this [Jira Task](https://curiositysoftware.atlassian.net/browse/GHTRIAGE-1) by [Unito](https://www.unito.io)

**Comment by mchassy** [comment]
@huwprice99  and @shashcuriosity 
I think we have an issue with the way the subflow data bubbles up into master models.
Please take a look and let me know if there are any questions.

**Comment by huwprice99** [comment]
I'd need an example set up on Partners to get my head around it.

**Comment by mchassy** [comment]
Reproduction of the issue

1. Create Model01 and declare Value01 as output
![image](https://user-images.githubusercontent.com/15926092/169078545-bf0543d4-968a-49f2-8c91-58f206cc3f04.png)

2. Create Model01-01, bring in model01 as a subflow, sync the mapping of Value01 and put it in Value01-01

![image](https://user-images.githubusercontent.com/15926092/169079468-8435e659-f5d1-43e4-8cad-71ca9876a508.png)

![image](https://user-images.githubusercontent.com/15926092/169079605-de04dbc6-6fca-42e4-bca5-00333f889cac.png)

![image](https://user-images.githubusercontent.com/15926092/169079745-ec16bbec-8717-42ce-bc38-b902386ef05d.png)

Data painter button not working if I create the variable here. It works if I close and come back.
![image](https://user-images.githubusercontent.com/15926092/169080332-3b990832-f702-43f7-9b8b-6731c053b61f.png)


Subflow variable not showing. 
![image](https://user-images.githubusercontent.com/15926092/169080635-9f88387c-56fb-4c6b-9ef5-801658062810.png)

It works if I save the model and come back
![image](https://user-images.githubusercontent.com/15926092/169081379-d38453ee-d308-4638-934f-c129f7cf9d65.png)

Assign Value01-01 with the value of Value01 from the subflow. Define it as outgoing as well (but not Value01)
![image](https://user-images.githubusercontent.com/15926092/169082236-555e6e7e-2ad1-4c22-92fe-0dfbf0d2e8d6.png)

Preview data
![image](https://user-images.githubusercontent.com/15926092/169082375-3510a067-b71f-40ec-a9f9-e6ceae4c8aea.png)

Do the same thing for Model01-02 and Value01-02. Don't have a proper screens shot, but the first time around Value01-02 does not properly take the value [Value01]. After doing the preview once and going back the order the variables appear changes and this second time the value takes.


Ok, now we have the data preview for Value01-02
![image](https://user-images.githubusercontent.com/15926092/169084346-07849285-519f-43fc-bb74-b7d602ab59b8.png)

Create Model04 which contains Model01-01 and Model01-02

![image](https://user-images.githubusercontent.com/15926092/169084874-47d20209-07d0-4b7f-8d62-9cb9a2354c73.png)

First data preview. Didn't do any subflow mapping.
![image](https://user-images.githubusercontent.com/15926092/169085129-f35862a0-41c9-4c7d-91f0-083c22cc49d0.png)

Saved as v1.01, closed and opened again. Still now subflow mapping, but some was done automatically.
![image](https://user-images.githubusercontent.com/15926092/169085562-6a525b6a-39b1-41a5-8403-5f63d008f3e4.png)

Forgot to map Value01-02 as ouput so went back and modified. For some reason when I map the out put for model01-02, it shows up as default value as well?? Got rid of it.
![image](https://user-images.githubusercontent.com/15926092/169087216-8950c15e-34ab-4360-b5b3-b89237b096ca.png)

Ran data preview again. Worked fine
![image](https://user-images.githubusercontent.com/15926092/169087564-0168e067-71cf-47c1-9868-66aba2f8e492.png)


But why is Value01 showing as a model variable when it should not have left the subflows?
![image](https://user-images.githubusercontent.com/15926092/169088590-4f353dbb-f99d-4a0d-a76e-306fd689394f.png)

It's not in the model variables ...
![image](https://user-images.githubusercontent.com/15926092/169088682-e403a30d-2508-4ae4-a410-6ec216ae832c.png)


so I have reproduced somewhat ...

**Comment by huwprice99** [comment]
Can you set up a call with me, Andrey and Rhys and show us on Partners what is going on?
